### ISSUE TITLE
Model checkpoints

### ISSUE THREAD

**Issue by irina-zys** [tikutikutiku/kaggle-hubmap#1]
Hi, many thanks for sharing your solution :)

I wonder if you still have the checkpoints for the trained model, and whether you would be willing to share the weights? Thanks!

**Comment by tikutikutiku** [comment]
The checkpoints in this notebook https://www.kaggle.com/code/tikutiku/hubmap-tilespadded-inference-v2 can be found here https://www.kaggle.com/datasets/tikutiku/hubmap-new-03-03

**Comment by irina-zys** [comment]
> The checkpoints in this notebook https://www.kaggle.com/code/tikutiku/hubmap-tilespadded-inference-v2 can be found here https://www.kaggle.com/datasets/tikutiku/hubmap-new-03-03

Many thanks!
